### ISSUE TITLE
Error when attempting to post-buffer-as-page with #+TITLE

### ISSUE THREAD

**Issue by willtm** [org2blog/org2blog#202] opened 2015-12-10 23:20 UTC
Hello,

I have an org file, `test.org`, that looks like this:

```
#+TITLE: blog

hey this is a page
```

When I use `M-x org2blog/wp-post-buffer-as-page-and-publish` I get an error (see http://pastebin.com/EiQ0EiDH )

But when I use the same command to post a page like this:

```
hey this is a page
```

It posts and publishes the page without any error (but also without a title).

I'd like to be able to troubleshoot the error above so that I can post the buffer with a title.  Can you help me get started?

**Comment by treese** [comment] 2015-12-11 17:24
I tried a quick test and it seemed to work for me. What versions of org-mode, emacs, and org2blog are you using?

**Comment by willtm** [comment] 2015-12-11 21:22
Treese,

Thanks for responding and my apologies for not including this information earlier:

Org-mode version 8.3.2 
GNU Emacs 25.0.50.1 (Windows 10) AND GNU Emacs 24.5 (Ubuntu 14.04
org2blog 20151208.828

I include both versions of Emacs because I have experienced the same issue with both instances.

Will

**Comment by treese** [comment] 2015-12-12 03:10
I have the same versions of org and org2blog, but I'm using Aquamacs 3.2 on the Mac, based on Emacs 24.4. The next step for debugging would probably be to load org.el before you try it, so that you get a better stack backtrace than with the compiled code.

**Comment by willtm** [comment] 2015-12-12 16:13
Treese,

Thanks for the reply.  I'm very new to the debugger and the step to removed byte-compiled files as a means of getting more readable backtrace messages seems obvious now but was new to me.  But, as it turns out, I don't have a backtrace because after I removed all the byte-compiled org-files, it worked as expected:  I was able to publish a file such as the one above, and the ```#+TITLE: test``` resulted in a page called ```test``` on my WP site.

I'm not sure why it worked though.  I'm tempted to recompile all the existing .el files in the elpa org directory to see if it still works...any suggestions?

**Comment by treese** [comment] 2015-12-14 02:53
@willtm The easiest thing if you are using ELPA is probably to reinstall the org package you are using, rather than trying to recompile them by hand.

**Comment by hexa00** [comment] 2016-03-30 15:50
Note I had a similar issue see : https://github.com/punchagan/org2blog/issues/209

Turned out my emacs internal org version & the version from elpa was conflicting.

Removing the elpa version worked... In your case maybe not having a byte compiled version changes the precedence of the org versions ?

What does M-x org-version say ?

**Comment by grettke** [comment] 2017-08-27 03:42
Try getting the latest version of Org-Mode and Org2Blog. I've been using it to publish pages successfully: https://github.com/grettke/wisdomandwonder/tree/master/page

I can't reproduce this so I am closing it. Don't hesitate to re-open it.

**Closed by grettke** 2017-08-27 03:42 UTC
