### ISSUE TITLE
Feature request: More "Vanilla" HTML

### ISSUE THREAD

**Issue by neonnoodle** [org2blog/org2blog#252] opened 2017-10-16 18:07 UTC
As of now, it appears that org2blog works by way of underlying functions in the org-to-html conversion system. I find the resulting HTML sometimes at odds with basic Wordpress HTML:

- **use of `<i>` and `<b>` instead of `<em>` and `<strong>`**. While not strictly "incorrect," Wordpress' default tag assignment for italic and bold are em and strong, and CSS may become a problem with inconsistent tags from **org2blog**.
- **extra `<div>` elements**. Upon creation of the post, each outline element is wrapped in a div tag. Again, this has the potential to cause CSS problems, and I don't see why they are needed in the post. Extra HTML can always be added by the user, but removing it can be time-consuming.
- **org-centric classes and ids added to elements**. In addition to the div wrapping, elements are given "outline" classes and generated id's. Lists get "org-ul" or "org-ol" classes. 

All in all, it would be nice to disable everything but the base elements (`<p>`, `<h1>`, `<h2>` etc., `<li/ol>`).

**Comment by titaniumbones** [comment] 2017-10-16 18:19
I think it would be easy to fix many of these issues by copying the relevant functions from `ox-html.el` and renaming + rewriting them in `ox-wp.el`. (I'm not sure about the extra div elements though). Do you want to submit a PR with those changes?

**Comment by grettke** [comment] 2017-10-17 01:09
I _think_ that we can make those changes as part of the export filter machinery. So we wouldn't have to copy or rewrite anything.

I'll look into it.

**Comment by grettke** [comment] 2017-12-16 17:33
@neonnoodle I read your post as a technical topic, and mentioned filtering. But I see now that you are talking about the format of the exported content being standardized. I've got two gut reactions immediately here.

#1 exporting HTML content that is structurally correct sounds great. That is always a good thing.

#2. Org-Mode already exports HTML content. What is unique to WordPress HTML content that we need to make any changes from that content for WordPress content? What kind of problems are you running into because of this?

The simplest thing to do here is to give you a pre-blog-post hook that gives you the entire body of the post as a string and let you make whatever changes that you want. 

@neonnoodle and @titaniumbones I need more help understanding where you run into problems, how you have worked around it or not, and whether or not a pre post hook would help you get what you want. I'm OK with the technical part but I don't understand the use cases for structure change.

**Comment by titaniumbones** [comment] 2017-12-18 17:07
@grettke I think that the issue is mostly that the html produced by org looks pretty different from the markup that the wordpress editor makes by default.  I myself have just finished moving all my courses over to Hugo so I have mostly stopped using org2blog in my daily life.  I can't think of a specific case where this divergence between org and WP markup caused problems for me, but I do think I encountered a few. I usually solved them with CSS, and probably that did lead to slightly unwieldy or hard-to-reproduce styling. But it's not immediately clear to me that altering the org markup would bring more benefits than problems.

**Comment by grettke** [comment] 2017-12-19 03:03
@titaniumbones Thank you for the explanation.

@neonnoodle That makes sense to produce vanilla WP HTML. Are you running into problems right now or is this a "nice to have"?

**Comment by neonnoodle** [comment] 2017-12-19 13:49
The issues I'm having relate to the extra `<div>` tags -- they can be a headache to remove and make editing with the visual editor annoying because they interfere with some types of formatting.

**Comment by grettke** [comment] 2017-12-20 18:40
I hear you. What I'm thinking is that I add a pre-post hook.

It gives you access to the body of the post right before it is posted.
There are 3 benefits:

1. Anybody can do anything to the body. In your example remove divs.

2. It makes debugging the post  body contents a little easier.

3. Avoids changing existing post content's structure. It's been this way
for a long time. That alone isn't a good reason to avoid changing it.
However I have no idea what it would change for anyone else. So I'd rather
not.

What do you think?

**Comment by bgturner** [comment] 2018-10-10 05:04
I'm just now getting into Orgmode and using it to publish to a blog, so I don't have any experience writing elisp (yet!). My main complaint so far is the extra divs and unnecessary IDs/classes.

This might be a dumb question, but within the pre-post hook will the "body" be basically a string of text that we have to apply some crazy regex too in order to strip out the unwanted markup?

**Comment by grettke** [comment] 2019-06-15 01:40
@bgturner Yes. The alternative is to write your content, export it to HTML, figure out what you want to change, and then configure Org to generate the HTML to your liking, and Org2Blog would just inherit your preferred setup.

**Comment by grettke** [comment] 2019-10-24 19:32
@bgturner If you are interested I'll help you do this. You wouldn't do it within Org2Blog. You would create a custom HTML exporter for Org mode that generated HTML to your preference. There are examples of how to do that (including in Org2Blog). It would take effort but it has been done before. Do you want to collaborate on something like this? It is the best way to get precisely what you want with the lowest effort possible. The regex would probably be the hardest part everything else is boilerplate. What do you think?

**Comment by grettke** [comment] 2020-02-27 03:12
Closing this issue because it is not active and it isn't obvious how to move forward with it. If work can start again then this task will get get re-opened.

**Closed by grettke** 2020-02-27 03:12 UTC
