### ISSUE TITLE
emacs window splits on posting

### ISSUE THREAD

**Issue by titaniumbones** [org2blog/org2blog#193] opened 2015-07-21 13:45 UTC
I'm trying to figure out what causes the current Emacs frame to split windows when posting to Wordpress using any of the org2blog/wp-post- functions.  I would like to suppress this behaviour if possible, especially since in general, the initial window loses focus and I tend to start typing in the wrong buffer!  

Does anyone else see this problem, and can you identify the origin? I believe it may arise from xlml-rpc or metaweblog, in which case it may be hard to debug properly.

Thanks everyone!

**Comment by aspiers** [comment] 2015-07-21 13:50
Yes I've seen this too and it is indeed annoying!  No idea what causes it though.

**Comment by titaniumbones** [comment] 2015-07-21 18:23
I made a trivial patch that fixes the problem for me:
https://github.com/punchagan/org2blog/commit/ef36181684b678447f74b1dfaacc8a896e1c27b5

Since my last pull request hasn't been merged, I can't create a new one for this patch alone. I would loveit if someone can test it.  

The problem is also fixed if ```org-export-show-temporary-export-buffer``` is set to nil (see ox-wp.el, near the end).  That might be the right solution, and is maybe something we cna mention in the README.

**Comment by aspiers** [comment] 2015-07-21 23:42
> I made a trivial patch that fixes the problem for me

Ah OK, it's a workaround rather than fixing the source of the issue.

> Since my last pull request hasn't been merged, I can't create a new one for this patch alone.

Why not?  Can't you put it in a separate branch?  Although I'm not sure it would be a good idea to merge this bandaid vs. preventing the split in the first place.

**Comment by titaniumbones** [comment] 2015-07-22 00:54
agreed.  anyway, it gets closer to identifying the source of the problem, whichI'm pretty sure is in ```org2blog/wp-upload-files-replace-urls``` as you can see if you instrument it with edebug.

**Comment by grettke** [comment] 2017-07-28 01:30
Setting `org-export-show-temporary-export-buffer` to true I can't reproduce this so I'm closing it.

**Closed by grettke** 2017-07-28 01:30 UTC

**Comment by priyadarshan** [comment] 2017-09-03 15:43
I had similar issue. As pointed out, `(setq org-export-show-temporary-export-buffer nil)` fixed it.

Thank you.

**Comment by averter** [comment] 2021-06-21 11:51
> I had similar issue. As pointed out, `(setq org-export-show-temporary-export-buffer nil)` fixed it.
> 
> Thank you.

Indeed. Thanks to both @priyadarshan @grettke
